name = "Relentleserver"
author = "Trcmoe"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1ea2bba7d6738334aae4258f0e0398a0dbb31ddcafa1b0d653fef29594b0d24"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
